from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.login_view, name='login'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('index/', views.index, name='index'),
    path('footer/', views.footer, name='footer'),
    path('head/', views.head, name='head'),
    path('header/', views.header, name='header'),
    path('navheader_view/', views.navheader_view, name='navheader_view'),
    path('sidebar/', views.index, name='sidebar'),
    path('app_calender/', views.app_calender, name='app_calender'),
    path('contact/', views.contact, name='contact'),
    path('performance/', views.performance, name='performance'),
    path('task/', views.task, name='task'),
    path('add_master_category/', views.add_category, name='add_category'),
    path('category_list/', views.category_list, name='category_list'),
    path('update_category/<int:category_id>/', views.update_category, name='update_category'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('sub_category/<int:category_id>/', views.subcategory_list, name='subcategory_list'),
    path('category_dropdown/', views.category_dropdown, name='category_dropdown'),
    path('add_sub_category/', views.add_sub_category, name='add_sub_category'),
    path('subcategory_list/', views.subcategory_list, name='subcategory_list'),
    path('update_subcategory/<int:id>/', views.update_subcategory, name='update_subcategory'),
    path('delete_subcategory/<int:id>/', views.delete_subcategory, name='delete_subcategory'),
    path('add_user/', views.add_user, name='add_user'),
    path('user_list/', views.user_list, name='user_list'),
    path('update_user/<int:user_id>/', views.update_user, name='update_user'),
    path('delete_user/<int:id>/', views.delete_user, name='delete_user'),
    path('employee/', views.employee, name='employee'),
    path('add_employee/', views.add_employee, name='add_employee'),
    path('employee_dropdown/', views.employee_dropdown, name='employee_dropdown'),
    path('employee_list/', views.employee_list, name='employee_list'),
    path('add_equipment/', views.add_equipment, name='add_equipment'),
    path('equipment_list/', views.equipment_list, name='equipment_list'),
    path('equipment_list/<int:subcategory_id>/', views.equipment_list, name='equipment_list'),
    path('delete_equipment_list/<int:id>/', views.delete_equipment_list, name='delete_equipment_list'),
    path('edit_subcategory_dropdown/', views.edit_subcategory_dropdown, name='edit_subcategory_dropdown'),
    path('edit_get_category_name/', views.edit_get_category_name, name='edit_get_category_name'),
    path('update_equipment/<int:id>/', views.update_equipment, name='update_equipment'),
    path('fetch_stock_status/<int:equipment_id>/', views.fetch_stock_status, name='fetch_stock_status'),
    path('fetch_serial_barcode_no/<int:equipment_id>/', views.fetch_serial_barcode_no, name='fetch_serial_barcode_no'),
    path('get_dimension_list/<int:equipment_id>/', views.get_dimension_list, name='get_dimension_list'),
    path('insert_vendor/', views.insert_vendor, name='insert_vendor'),
    path('subcategory_dropdown/', views.subcategory_dropdown, name='subcategory_dropdown'),
    path('get_category_name/', views.get_category_name, name='get_category_name'),
    path('Stock_list/', views.Stock_list, name='Stock_list'),
    path('fetch-equipment-list/', views.fetch_equipment_list, name='fetch_equipment_list'),
    path('stock-in/<int:equipment_id>/', views.stock_in, name='stock_in'),
    path('update-stock-in/<int:row_id>/', views.update_stock_in, name='update-stock-in'),
    path('fetch_stock_details_by_name/', views.fetch_stock_details_by_name, name='fetch_stock_details_by_name'),
    path('add_event_view/', views.add_event_view, name='add_event_view'),
    path('get_eventvalue/', views.get_eventvalue, name='get_eventvalue'),
    path('modify_employee/', views.modify_employee, name='modify_employee'),
    path('delete_attachment/', views.delete_attachment, name='delete_attachment'),
    path('add_job/', views.add_job, name='add_job'),
    path('fetch_client_name/', views.fetch_client_name, name='fetch_client_name'),
    path('fetch_venue_addresses/', views.fetch_venue_addresses, name='fetch_venue_addresses'),
    path('get_new_row_data/', views.get_new_row_data, name='get_new_row_data'),
    path('fetch_master_categories/', views.fetch_master_categories, name='fetch_master_categories'),
    path('fetch_equipment_names/', views.fetch_equipment_names, name='fetch_equipment_names'),
    path('fetch_rental_price/', views.fetch_rental_price, name='fetch_rental_price'),
    path('save_row_data/', views.insert_data, name='save_row_data'),
    path('get_employee_name/', views.get_employee_name, name='get_employee_name'),
    path('delete_row_from_temp_table/', views.delete_row_from_temp_table, name='delete_row_from_temp_table'),
    path('jobs_list/', views.jobs_list, name='jobs_list'),
    path('get_status_counts/', views.get_status_counts, name='get_status_counts'),
    path('update_jobs/<int:id>/', views.update_jobs, name='update_jobs'),
    path('delete_jobs/<int:id>/', views.delete_jobs, name='delete_jobs'),
    path('add_connects/', views.add_connects, name='add_connects'),
    path('connect_list/', views.connect_list, name='connect_list'),
    path('company_dropdown_view/', views.company_dropdown_view, name='company_dropdown_view'),
    path('update_connect/<int:id>/', views.update_connect, name='update_connect'),
    path('delete_connect/<int:id>/', views.delete_connect, name='delete_connect'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
